App:
  server:
    http:
      bindIp: "127.0.0.1"
      bindPort: 8080
      contextPath: ""
  datastore:
    mongo:
      # for single node replica set directConnection=true flag needed
      url: "mongodb://localhost:27017/?directConnection=true"
      username: "mongoadmin"
      password: "secret"
